// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.dto;

import com.app.dto.StudentSearchDto;
import io.springlets.format.EntityFormat;

privileged aspect StudentSearchDto_Roo_DTO {
    
    declare @type: StudentSearchDto: @EntityFormat;
    
}
