// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.repository;

import com.app.repository.StudentRepository;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StudentRepository_Roo_Jpa_Repository {
    
    declare @type: StudentRepository: @Transactional(readOnly = true);
    
}
