// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.app.web;

import com.app.web.StudentsItemRegisteredCoursesThymeleafController;
import com.app.web.StudentsItemRegisteredCoursesThymeleafLinkFactory;
import io.springlets.web.mvc.util.MethodLinkFactory;
import io.springlets.web.mvc.util.SpringletsMvcUriComponentsBuilder;
import java.util.Map;
import org.springframework.stereotype.Component;
import org.springframework.web.util.UriComponents;

privileged aspect StudentsItemRegisteredCoursesThymeleafLinkFactory_Roo_LinkFactory {
    
    declare parents: StudentsItemRegisteredCoursesThymeleafLinkFactory implements MethodLinkFactory<StudentsItemRegisteredCoursesThymeleafController>;
    
    declare @type: StudentsItemRegisteredCoursesThymeleafLinkFactory: @Component;
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String StudentsItemRegisteredCoursesThymeleafLinkFactory.DATATABLES = "datatables";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String StudentsItemRegisteredCoursesThymeleafLinkFactory.DATATABLESBYIDSIN = "datatablesByIdsIn";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String StudentsItemRegisteredCoursesThymeleafLinkFactory.CREATEFORM = "createForm";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String StudentsItemRegisteredCoursesThymeleafLinkFactory.REMOVEFROMREGISTEREDCOURSES = "removeFromRegisteredCourses";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String StudentsItemRegisteredCoursesThymeleafLinkFactory.REMOVEFROMREGISTEREDCOURSESBATCH = "removeFromRegisteredCoursesBatch";
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    public static final String StudentsItemRegisteredCoursesThymeleafLinkFactory.CREATE = "create";
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return Class
     */
    public Class<StudentsItemRegisteredCoursesThymeleafController> StudentsItemRegisteredCoursesThymeleafLinkFactory.getControllerClass() {
        return StudentsItemRegisteredCoursesThymeleafController.class;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param methodName
     * @param parameters
     * @param pathVariables
     * @return UriComponents
     */
    public UriComponents StudentsItemRegisteredCoursesThymeleafLinkFactory.toUri(String methodName, Object[] parameters, Map<String, Object> pathVariables) {
        if (methodName.equals(DATATABLES)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatables(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(DATATABLESBYIDSIN)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).datatablesByIdsIn(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATEFORM)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).createForm(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMREGISTEREDCOURSES)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromRegisteredCourses(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(REMOVEFROMREGISTEREDCOURSESBATCH)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).removeFromRegisteredCoursesBatch(null, null)).buildAndExpand(pathVariables);
        }
        if (methodName.equals(CREATE)) {
            return SpringletsMvcUriComponentsBuilder.fromMethodCall(SpringletsMvcUriComponentsBuilder.on(getControllerClass()).create(null, null, null, null, null)).buildAndExpand(pathVariables);
        }
        throw new IllegalArgumentException("Invalid method name: " + methodName);
    }
    
}
